name: Run Rover Subgraph Lint
description: Run the `rover subgraph lint` command
author: Apollo GraphQL
branding:
  icon: terminal

inputs:
  # required
  apollo-key:
    description: Your Apollo Studio API key
    required: true
  graph-ref:
    description: <NAME>@<VARIANT> of graph in Apollo Studio
    required: true
  name:
    description: The name of the subgraph
    required: true
  schema:
    description: The schema file to check
    required: true

  # optional
  ignore-existing-lint-violations:
    description: (Optional) If provided, the linter only flags violations that are present in the diff between your local schema and your published schema.By default, this command flags all violations in your local schema.

  # common
  log:
    description: Specify Rover's log level
  format:
    description: Specify Rover's log format type [plain|json]
  client-timeout:
    description: Configure the timeout length (in seconds) when performing HTTP(S) requests

runs:
  using: composite
  steps:
    - env:
        APOLLO_KEY: ${{ inputs.apollo-key }}
      run: |
        ARGS=(${{ inputs.graph-ref }} --name ${{ inputs.name }} --schema ${{ inputs.schema }})
        [ "${{ inputs.ignore-existing-lint-violations }}" == "true" ] && ARGS+=(--ignore-existing-lint-violations)
        [ -n "${{ inputs.log }}" ] && ARGS+=(--log ${{ inputs.log }})
        [ -n "${{ inputs.format }}" ] && ARGS+=(--format ${{ inputs.format }})
        [ -n "${{ inputs.client-timeout }}" ] && ARGS+=(--client-timeout ${{ inputs.client-timeout }})

        rover subgraph lint ${ARGS[@]}
      shell: bash
